''' <summary>
''' The Listing Class. This represents a product that is ready to be listed externally. For instance on eBay or Amazon.
''' </summary>
Public Class clsListing
    Inherits EskimoBaseClass
    Enum ListingTypeEnum

        ''' <summary>
        ''' eBay
        ''' </summary>
        eBay = 1

        ''' <summary>
        ''' Amazon
        ''' </summary>
        Amazon = 2
    End Enum
    Enum ListingFormatEnum
        ''' <summary>
        ''' http://pages.ebay.co.uk/help/buy/buyer-bin.html
        ''' </summary>
        BuyItNow = 8
        ''' <summary>
        ''' http://pages.ebay.co.uk/help/sell/auction.html
        ''' </summary>
        Auction = 4
    End Enum
    Enum ListingDurationEnum
        ThreeDays = 3
        FiveDays = 5
        SevenDays = 7
        TenDays = 10
        ThirtyDays = 30
        UntilCancelled = -1
    End Enum

    Enum DispatchTimeMaxEnum
        SameWorkingDay = 0
        OneWorkingDay = 1
        TwoWorkingDays = 2
        ThreeWorkingDays = 3
    End Enum
    Enum ConditionEnum
        ''' <summary>
        ''' A brand-new, unused, unopened, unworn, undamaged item. Most categories support this condition (as long as condition is an applicable concept).
        ''' </summary>
        [New] = 1000

        ''' <summary>
        ''' A brand-new, unused, and unworn item. The item may have cosmetic defects, and/or may contain mismarked tags (e.g., incorrect size tags from the manufacturer). Packaging may be missing or opened. The item may be a new factory second or irregular.
        ''' </summary>
        NewWithDefects = 1750

        ''' <summary>
        ''' An item in excellent condition that has been professionally restored to working order by a manufacturer or manufacturer-approved vendor. The item may or may not be in the original packaging.
        ''' </summary>
        ManufacturerRefurbished = 2000

        ''' <summary>
        ''' An item that has been restored to working order by the eBay seller or a third party who is not approved by the manufacturer. This means the seller indicates that the item is in full working order and is in excellent condition. The item may or may not be in original packaging.
        ''' </summary>
        SellerRefurbished = 2500


        ''' <summary>
        ''' An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. Most categories support this condition (as long as condition is an applicable concept).
        ''' </summary>
        Used = 3000

        ''' <summary>
        ''' An item that is used but still in very good condition. No obvious damage to the cover or jewel case. No missing or damaged pages or liner notes. The instructions (if applicable) are included in the box. May have very minimal identifying marks on the inside cover. Very minimal wear and tear.
        ''' </summary>
        VeryGood = 4000

        ''' <summary>
        ''' An item in used but good condition. May have minor external damage including scuffs, scratches, or cracks but no holes or tears. For books, liner notes, or instructions, the majority of pages have minimal damage or markings and no missing pages.
        ''' </summary>
        Good = 5000

        ''' <summary>
        ''' An item with obvious or significant wear, but still operational. For books, liner notes, or instructions, the item may have some damage to the cover but the integrity is still intact. Instructions and/or box may be missing. For books, possible writing in margins, etc., but no missing pages or anything that would compromise the legibility or understanding of the text.
        ''' </summary>
        Acceptable = 6000

        ''' <summary>
        ''' An item that does not function as intended and is not fully operational. This includes items that are defective in ways that render them difficult to use, items that require service or repair, or items missing essential components. Supported in categories where parts or unworking items are of interest to people who repair or collect related items.
        ''' </summary>
        ForPartsOrNotWorking = 7000

    End Enum

    ''' <summary>
    ''' The numeric Eskimo ID of the Listing
    ''' </summary>
    ''' <returns></returns>
    Property EskimoID As Integer

    ''' <summary>
    ''' The Identifier used by the third-party site. For example, when listing an item on eBay, an ID will generated by eBay to represent that listing.
    ''' </summary>
    ''' <returns></returns>
    Property ExternalID As String

    ''' <summary>
    ''' Listing Type, or destination for the listing.
    ''' </summary>
    ''' <returns></returns>
    Property ListingType As ListingTypeEnum

    ''' <summary>
    ''' The external category. The ID of this will be required to post the item on the third-party site.
    ''' </summary>
    ''' <returns></returns>
    Property Category As clsExternalCategory

    ''' <summary>
    ''' The date that the retailer created the listing within the Eskimo software.
    ''' </summary>
    ''' <returns></returns>
    Property DateCreatedLocally As Date

    ''' <summary>
    ''' The date that the listing was posted to the third-party. This will be NULL until the MarkAsListed action is called.
    ''' </summary>
    ''' <returns></returns>
    Property DateListedExternally As Date

    ''' <summary>
    ''' This is the short Title of the product being listed.
    ''' </summary>
    ''' <returns></returns>
    Property Title As String

    ''' <summary>
    ''' This is the full HTML description of the item.
    ''' </summary>
    ''' <returns></returns>
    Property ItemDescription As String

    ''' <summary>
    ''' This determines if the listing will be using more than one SKU. For instance, a t-shirt that comes in multiple colours and sizes will set this to True.
    ''' </summary>
    ''' <returns></returns>
    ReadOnly Property UsesVariations As Boolean
        Get
            If Me.Variations Is Nothing Then Return False
            Return Me.Variations.Count > 1
        End Get
    End Property
    ''' <summary>
    ''' The amount of time that the listing should be active for
    ''' </summary>
    ''' <returns></returns>
    Property ListingDuration As ListingDurationEnum

    ''' <summary>
    ''' How long the retailler will take to dispatch the goods once an order is placed.
    ''' </summary>
    ''' <returns></returns>
    Property MaxDispatchTime As DispatchTimeMaxEnum

    ''' <summary>
    ''' The condition of the product.
    ''' </summary>
    ''' <returns></returns>
    Property ItemCondition As ConditionEnum

    ''' <summary>
    ''' Determines if the product should be relisted if it doesn't sell
    ''' </summary>
    ''' <returns></returns>
    Public Property Auto_Relist As Boolean

    ''' <summary>
    ''' Fixed Price or Auction
    ''' </summary>
    ''' <returns></returns>
    Public Property Listing_Format As ListingFormatEnum = ListingFormatEnum.BuyItNow

    ''' <summary>
    ''' Are returns accepted for this product
    ''' </summary>
    ''' <returns></returns>
    Public Property Returns_Accepted As Boolean

    ''' <summary>
    ''' The currency code used for the listing
    ''' </summary>
    ''' <returns></returns>
    Property CurrencyCode As String

    ''' <summary>
    ''' The two-digit country code for the lister of the product
    ''' </summary>
    ''' <returns></returns>
    Property CountryCode As String

    ''' <summary>
    ''' A collection of the Item Specifics about this product. These are completed by the retailer, using the suggestions provided by the third-party. For instance, eBay will provide a list of all key-value pairs that they would like completed for each category type.
    ''' </summary>
    ''' <returns></returns>
    Property ItemSpecifics As IEnumerable(Of clsItemSpecificsBasic)

    ''' <summary>
    ''' If this listing is set to use variation, then this will be a collection of the price, SKU and quantity in stock that are offered for the product being listed. If the product does not use Variations, then there will only be one entry present.
    ''' </summary>
    ''' <returns></returns>
    Property Variations As IEnumerable(Of clsVariation)

    ''' <summary>
    ''' A collection of the shipping options offered for the listing. For example they might offer Collect in Person + Parcel force 24 hour.
    ''' </summary>
    ''' <returns></returns>
    Property ShippingDetails As IEnumerable(Of clsListingShipping)

    ''' <summary>
    ''' A collection of images for the listing
    ''' </summary>
    ''' <returns></returns>
    Property ListingImages As IEnumerable(Of clsListingImage)

End Class

Public Class clsListingShipping
    Inherits EskimoBaseClass

    ''' <summary>
    ''' The row count
    ''' </summary>
    ''' <returns></returns>
    Property Index As Integer

End Class